In [ ]:
import numpy as np
import random

In [ ]:
# 1 to 3 or 1  to 5. let sa we choose to go to 3. if we go to 3, from 3 either we will comeback or go to 6.
# 3 < 1 > 5 1<3>6
# Q(s,a) = Q(s,a) + alpha(R(s,s) + gamma*max(Q(s',a')) - Q(s,a))

In [ ]:
q_table = np.array([
    [2.0,  4.0],  # State 0
    [6.0,  5.0]   # State 1
])
learning_rate = 0.1
discount_factor = 0.9
reward = 3.0
q_new = 4 + learning_rate*(reward + discount_factor*max(q_table[1]) - 4)
print("q_new: ",q_new)
# q_new:  4.44

q_new:  4.44


In [ ]:
row_of_q_table = np.array([1.5, 5.0, 0.2])
eps = 0.3
def get_action(q_values, epsilon):
    random_number = random.uniform(0, 1)

    if random_number < epsilon:
        # --- EXPLORATION ---
        print("Mode: Exploration (Random)")
        action = random.randint(0, len(q_values) - 1)
    else:
        # --- EXPLOITATION ---
        print("Mode: Exploitation (Best Known)")
        action = np.argmax(q_values)

    return action

chosen_action = get_action(row_of_q_table, eps)
print(f"Action Index Selected: {chosen_action}")

Mode: Exploration (Random)
Action Index Selected: 1


In [ ]:
learning_rate = 0.1
discount_factor = 0.9
epsillon = 3.0
# <Action-0> Up	<Action-1> Down	<Action-2> Pickup
q_table = np.array([
    [4.0, 2.5, 1.00],  # State 5
    [3.0, 5.0, 10.0]   # State 6
])
# new value for Q(State 5, Down)
q_new = 2.5 + learning_rate*(-2 + discount_factor*max(q_table[1]) - 2.5)
print("q_new: ",q_new)


q_new:  2.95


In [ ]:
# q learning
rewards = np.array([
    #  A     B     C    D     E     F
    [-1.0, -1.0,  0.0, 1.0, -1.0, -1.0], # F
    [-1.0, 1.0, -1.0,  0.0, -1.0,  0.0], # E
    [-1.0,  5.0,  0.0,  0.0, -1.0,  0.0], # D
    [-1.0, -1.0, -1.0, -1.0,  0.0,  0.0], # C
    [10.0, 0.0,  0.0,  0.0,  0.0, -1.0], # B <<<
    [-1.0,  0.0, -1.0,  0.0,  0.0,  0.0]  # A
])
q_table = np.array([
    # A    B    C    D    E    F
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # F
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # E
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # D
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # C
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # B <<<
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # A
])
qsa_preserve = []
# initial state B, A is goal
a = 0.2
Y = 0.9
C = q_table[3] # [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # C
E = q_table[1] # [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # E
D = q_table[2] # [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # D
B = q_table[4] # [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # B
A = q_table[5] # [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # A
q_sa = 0 # current state F

next_state = C # future state when in F
# q_s_a = q_s_a + a*(R + Y*max(q_s_a_p) - q_s_a)
qsa = 0 + 0.2*(0 + 0.9*max(0.0, 0.0, 0.0, 0.0, 0.0, 0.0) - 0)
qsa_preserve.append(qsa)
# print("qsa: ",qsa) # qsa:  0.0
q_table[0][2] = qsa

next_state = E # future state when in C
qsa = 0 + 0.2*(0 + 0.9*max(0.0, 0.0, 0.0, 0.0, 0.0, 0.0) - 0)
qsa_preserve.append(qsa)
# print("qsa: ",qsa) # qsa:  0.0
q_table[3][4] = qsa

next_state = D # future state when in E
qsa = 0 + 0.2*(0 + 0.9*max(0.0, 0.0, 0.0, 0.0, 0.0, 0.0) - 0)
qsa_preserve.append(qsa)
# print("qsa: ",qsa) # qsa:  0.0
q_table[1][3] = qsa

next_state = B # future state when in D
qsa = 0 + 0.2*(5.0 + 0.9*max(0.0, 0.0, 0.0, 0.0, 0.0, 0.0) - 0)
qsa_preserve.append(qsa)
# print("qsa: ",qsa) # qsa:  1.0
q_table[2][1] = qsa

next_state = A # future state when in B
qsa = 0 + 0.2*(10.0 + 0.9*max(0.0, 0.0, 0.0, 0.0, 0.0, 0.0) - 0)
qsa_preserve.append(qsa)
# print("qsa: ",qsa) # qsa:  2.0
q_table[4][0] = qsa

# print("updated q table: ")
# print(q_table)
# updated q table:
# [[0. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0.]
#  [0. 1. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0.]
#  [2. 0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0. 0.]]

In [ ]:
qsar = 15
a = 0.5
Y = 0.9
future_value = 5.0
R = 10
qsar = qsar + a*(R + Y*(future_value) - qsar)
print("Sarsa: ", qsar) # Sarsa:  14.75

Sarsa:  14.75


In [ ]:
# sarsa
rewards = np.array([
    #  A     B     C    D     E     F
    [-1.0, -1.0,  0.0, 1.0, -1.0, -1.0], # F <<<
    [-1.0, 1.0, -1.0,  0.0, -1.0,  0.0], # E
    [-1.0,  0.5,  0.0,  0.0, -1.0,  0.0], # D
    [-1.0, -1.0, -1.0, -1.0,  0.0,  0.0], # C
    [1.0, 0.0,  0.0,  0.0,  0.0, -1.0], # B
    [-1.0,  0.0, -1.0,  0.0,  0.0,  0.0]  # A
])
q_table = np.array([
    # A    B    C    D    E    F
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # F <<<
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # E
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # D
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # C
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0], # B
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]  # A
])
current_state = rewards[0]
a = 0.2
y = 0.9
eps = 0.5
# ---- choose action at F (exploit) ----
action = np.argmax(current_state)
R = rewards[0][action]
# ---- current Q(s,a) ----
qsar = q_table[0][action]
# ---- next state ----
next_state_index = action
# next action at s′ (exploit)
next_action = np.argmax(q_table[next_state_index])
# Q(s′,a′)
next_q = q_table[next_state_index][next_action]

qsar = qsar + a * (R + y * next_q - qsar)
print("qsar:", qsar)

qsar: 0.2
